env:
  - GO111MODULE=on
  - GOPROXY=direct
before:
  hooks:
    - go mod download

builds:
  - id: kubefwd
    main: ./cmd/kubefwd/kubefwd.go
    binary: kubefwd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
      - -a
      - -v
    ldflags: -s -w -X main.Version={{.Version}}

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

release:
  github:
    owner: c6o
    name: kubefwd
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
